CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE Burger
(
	id int NOT NULL AUTO_INCREMENT,
	burger_name varchar(255) NOT NULL,
	devoured BOOLEAN DEFAULT false,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAT TIMESTAMP 0 ON UPDATE CURRENT_TIMESTAMP
	PRIMARY KEY (id)
);
